version: '3.8'

services:
  vue-dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
